### ISSUE TITLE
Change parsing string?

### ISSUE THREAD

**Issue by pketelaar** [BritishTechGuru/PI-Pico-L76B#1]
This is great because their code sucked!

One question - How would you change this to parse the the GGA Sentence? I would like to see altitude. 

I think that the l76x.py would need to change this area right? 

```

def L76X_Gat_GNRMC(self):
#we are only after the GNRMC field and only want:
# latitude, longtitude, direction, time and speed. Nothing else is of
# any importance - maybe data valid might be needed - don't yet know
        data = self.config.Uart_ReceiveString(BUFFSIZE)
        stringy = data.decode('UTF-8')
        StLen = len(stringy)
        if (stringy.find("$GNRMC") >-1):
#crop everything before the first field
            StartPoint = stringy.index("$GNRMC")+7
            stringy = stringy[StartPoint: (StLen - StartPoint)]    
#crop everything from the second $        
            EndPoint = stringy.index("$")
            stringy = stringy[0:EndPoint]
#now make it into a list
            Listy = stringy.split(',')
            RSTime = Listy[0]
            RSValid = Listy[1]
            RSLattitude = Listy[2]
            RSNSHemisphere = Listy[3]
            RSLongtitude = Listy[4]
            RSWEHemisphere = Listy[5]
            RSGroundSpeed = Listy[6]
            RSDirection = Listy[7]
            RSDate = Listy[8]
            RSVariation = Listy[9]
            RSChecksum = Listy[10]
#now return the required values to the program. That, for the drone operation will be
            return RSTime, RSLattitude, RSLongtitude, RSGroundSpeed, RSDirection, RSDate, RSVariation

```

**Comment by pketelaar** [comment]
So i've tried modifying (commenting out the GNRMC) and using this in the l76x.py file:

````
    def L76X_Gat_GNGGA(self):
#we are only after the GNGGA field and only want:
# latitude, longtitude, altitude, time and speed. Nothing else is of
# any importance - maybe data valid might be needed - don't yet know
        data = self.config.Uart_ReceiveString(BUFFSIZE)
        stringy = data.decode('UTF-8')
        StLen = len(stringy)
        if (stringy.find("$GNGGA") >-1):
#crop everything before the first field
            StartPoint = stringy.index("$GNGGA")+7
            stringy = stringy[StartPoint: (StLen - StartPoint)]    
#crop everything from the second $        
            EndPoint = stringy.index("$")
            stringy = stringy[0:EndPoint]
#now make it into a list
            Listy = stringy.split(',')
            RSTime = Listy[0]
            RSLattitude = Listy[1]
            RSNSHemisphere = Listy[2]
            RSLongtitude = Listy[3]
            RSWEHemisphere = Listy[5]
            RSFixType = Listy[6]
            RSNumSats = Listy[7]
            RSHDOP = Listy[8]
            RSAltitude = Listy[9]
            RSAltitudeUnits = Listy[10]
            RSHMSL = Listy[11]
            RSUnitsGeoid = Listy[12]
            RSTSLDC = Listy[13]
            RSDiffSID = Listy[14]
            RSChecksum = Listy[15]
#now return the required values to the program. That, for the operation will be
            return RSTime, RSLattitude, RSLongtitude, RSAltitude, RSDate

````
then modifying the main file to include (ignore the lcd stuff, im using a waveshare attached LCD display):

````
while(1):
    
    RSTime, RSLattitude, RSLongtitude, RSAltitude, RSDate = x.L76X_Gat_GNGGA()

    print ("Time : ", RSTime)
    print ("Lattitude : ", RSLattitude)
    print ("Longtitude : ", RSLongtitude)
    print ("Altitude : ", RSAltitude)
    #print ("Ground speed in knots : ", RSGroundSpeed)
    #print ("Compass direction : ", RSDirection)
    print ("Today's date : ", RSDate)
    #print ("Magnetic Variation : ", RSVariation)
    print ("--------------------------------------------")
    lcd = LCD_0inch96()   
    #lcd.fill(BLACK)
    colorlist = [RED, BLUE, GREEN, WHITE, PURPLE, NAVY, MAGENTA, CYAN, YELLOW, ORANGE, PINK]
    lcd.text("Time:"+str(RSTime),20,0,WHITE)
    lcd.text("Date:"+str(RSDate),20,11,WHITE)
    lcd.text("Alt:"+str(RSAltitude),20,21,WHITE)
    lcd.text("Lat:"+str(RSLattitude),20,32,WHITE)
    lcd.text("Long:"+str(RSLongtitude),20,42,WHITE)
        
    lcd.display()
        #z = z + 1
    time.sleep(5)
    #lcd.fill(BLACK)


    #time.sleep(5)

````

but I get an error that line 143 valueerror substring not found, referring to this line: 

            EndPoint = stringy.index("$")


````


>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 257, in <module>
  File "l76x.py", line 143, in L76X_Gat_GNGGA
ValueError: substring not found
>>> 

````

**Comment by BritishTechGuru** [comment]
Substring not found would suggest to me that you’re looking beyond the length of the array or list. Are you sure that your glonass sentence is being read? I used one gps sentence, partly because it had all the information I needed but also because I never really researched the glonass stuff.

I would suggest verifying that the glonass sentence has been read as a first priority.

Sent from my iPad

On Nov 2, 2022, at 4:49 PM, pketelaar ***@***.******@***.***>> wrote:


So i've tried modifying (commenting out the GNRMC) and using this in the l76x.py file:

    def L76X_Gat_GNGGA(self):
#we are only after the GNGGA field and only want:
# latitude, longtitude, altitude, time and speed. Nothing else is of
# any importance - maybe data valid might be needed - don't yet know
        data = self.config.Uart_ReceiveString(BUFFSIZE)
        stringy = data.decode('UTF-8')
        StLen = len(stringy)
        if (stringy.find("$GNGGA") >-1):
#crop everything before the first field
            StartPoint = stringy.index("$GNGGA")+7
            stringy = stringy[StartPoint: (StLen - StartPoint)]
#crop everything from the second $
            EndPoint = stringy.index("$")
            stringy = stringy[0:EndPoint]
#now make it into a list
            Listy = stringy.split(',')
            RSTime = Listy[0]
            RSLattitude = Listy[1]
            RSNSHemisphere = Listy[2]
            RSLongtitude = Listy[3]
            RSWEHemisphere = Listy[5]
            RSFixType = Listy[6]
            RSNumSats = Listy[7]
            RSHDOP = Listy[8]
            RSAltitude = Listy[9]
            RSAltitudeUnits = Listy[10]
            RSHMSL = Listy[11]
            RSUnitsGeoid = Listy[12]
            RSTSLDC = Listy[13]
            RSDiffSID = Listy[14]
            RSChecksum = Listy[15]
#now return the required values to the program. That, for the operation will be
            return RSTime, RSLattitude, RSLongtitude, RSAltitude, RSDate



then modifying the main file to include (ignore the lcd stuff, im using a waveshare attached LCD display):

while(1):

    RSTime, RSLattitude, RSLongtitude, RSAltitude, RSDate = x.L76X_Gat_GNGGA()

    print ("Time : ", RSTime)
    print ("Lattitude : ", RSLattitude)
    print ("Longtitude : ", RSLongtitude)
    print ("Altitude : ", RSAltitude)
    #print ("Ground speed in knots : ", RSGroundSpeed)
    #print ("Compass direction : ", RSDirection)
    print ("Today's date : ", RSDate)
    #print ("Magnetic Variation : ", RSVariation)
    print ("--------------------------------------------")
    lcd = LCD_0inch96()
    #lcd.fill(BLACK)
    colorlist = [RED, BLUE, GREEN, WHITE, PURPLE, NAVY, MAGENTA, CYAN, YELLOW, ORANGE, PINK]
    lcd.text("Time:"+str(RSTime),20,0,WHITE)
    lcd.text("Date:"+str(RSDate),20,11,WHITE)
    lcd.text("Alt:"+str(RSAltitude),20,21,WHITE)
    lcd.text("Lat:"+str(RSLattitude),20,32,WHITE)
    lcd.text("Long:"+str(RSLongtitude),20,42,WHITE)

    lcd.display()
        #z = z + 1
    time.sleep(5)
    #lcd.fill(BLACK)


    #time.sleep(5)



but I get an error that line 143 valueerror substring not found, referring to this line:

        EndPoint = stringy.index("$")




>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 257, in <module>
  File "l76x.py", line 143, in L76X_Gat_GNGGA
ValueError: substring not found

**Comment by 000096** [comment]
hi
The code is grate but i want to know "from machine import Pine"  what is "machine"

**Comment by BritishTechGuru** [comment]
> hi The code is grate but i want to know "from machine import Pine" what is "machine"

from machine import Pin - this means import the Pin subsection of the machine library. Instead of loading the whole of the machine library, we're just loading the bit we need.

**Comment by 000096** [comment]
Thank you for your reply,but when i run "micropython main.py"

The program will report an error and prompt ”ImportError: no module named 'Pin'“.I don't know how to deal with it? Is it my hardware version?thank u










                       
原始邮件
                       
                     

发件人："Zephod Beeblebrox"< ***@***.*** &gt;;

发件时间：2023/3/13 1:38

收件人："BritishTechGuru/PI-Pico-L76B"< ***@***.*** &gt;;

抄送人："000096"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [BritishTechGuru/PI-Pico-L76B] Change parsing string? (Issue #1)




  
hi The code is grate but i want to know "from machine import Pine" what is "machine"
  
from machine import Pin - this means import the Pin subsection of the machine library. Instead of loading the whole of the machine library, we're just loading the bit we need.
 
&mdash;

**Comment by BritishTechGuru** [comment]
> Thank you for your reply,but when i run "micropython main.py" The program will report an error and prompt ”ImportError: no module named 'Pin'“.I don't know how to deal with it? Is it my hardware version?thank u

That is very curious and I can only say that I am running the software with the Pi Pico with Python from the Raspberry Pi website. I think once I fixed the buggy original software, it ran perfectly.

Have you included the machine library using Thonny?

**Comment by 000096** [comment]
thank u，i have already fix the code which i download from offical websit。







                       
原始邮件
                       
                     

发件人："Zephod Beeblebrox"< ***@***.*** &gt;;

发件时间：2023/3/14 5:18

收件人："BritishTechGuru/PI-Pico-L76B"< ***@***.*** &gt;;

抄送人："000096"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [BritishTechGuru/PI-Pico-L76B] Change parsing string? (Issue #1)




  
Thank you for your reply,but when i run "micropython main.py" The program will report an error and prompt ”ImportError: no module named 'Pin'“.I don't know how to deal with it? Is it my hardware version?thank u
  
That is very curious and I can only say that I am running the software with the Pi Pico with Python from the Raspberry Pi website. I think once I fixed the buggy software, it ran perfectly.
 
&mdash;

**Comment by BritishTechGuru** [comment]
_Thank you for your reply,but when i run "micropython main.py" The program will report an error and prompt ”ImportError: no module named 'Pin'“.I don't know how to deal with it? Is it my hardware version?thank u_

As far as I can recall I had no issues with Pin or Machine. If i did, they were resolved using the resources on the Raspberry website. It must have been close to a year since I worked with the GPS module. It's still attached to one of my Pi Picos but I'd have to find it and right now it's 5am and I have to head to work.

The problem you're encountering seems more related to something that has not been installed via Thonny. It is possible that they might have updated the firmware on newer Picos such that Pin is no longer in Machine. That I know nothing about.

Perhaps the question on Pin/Machine might be better asked on the Raspberry Pi website? Mastodon is also a good resource with people actually willing to answer questions. If I recall correctly then I might have done a video on this GPS module. Try here: http://www.britishtechguru.org
